### PR TITLE
Create Video To Text - Step 1 - ReadMe

### PR DESCRIPTION
**Pull request by ChiragBellara**
Adding a readme file indicating the general information about the code.

Note: The code that is uploaded (IPYNB file) also contains relevant comments.

### CODE REVIEW

**Comment by zeshengchen** [comment]
I would expect that for a pull request, it is not just a readme file. Please come up with code/changes with the readme!

**Comment by ChiragBellara** [comment]
Yes. This is just the first commit. There will be a code commit as well.

**Comment by SaiSurajMatta** [comment]
Readme file explains the first step clearly. looks good.

**Comment by silbunsa** [comment]
Looks good :)

**Comment by ChiragBellara** [comment]
Please review this request but do not close it. I will merge and close it myself.
@SaiSurajMatta @silbunsa @roh-it

**Comment by silbunsa** [comment]
Looks good! !

**Review by roh-it — APPROVED** [review]
LGTM

**Review by silbunsa — APPROVED** [review]

**Review by SaiSurajMatta — APPROVED** [review]

**Pull request merged**
