### PR TITLE
Added Code File and changed folder structure

### PR DESCRIPTION
**Pull request by ChiragBellara**
I have added the Code for the first step as mentioned in the readme file.
Please go through the code and let me know if there are any changes or enhancements that I should make to it.

I have also put the code and readme file in a folder titled "VideoToText". That is just to enhance readability and has nothing to do with the functionality of the code.

### CODE REVIEW

**Review by zeshengchen — CHANGES_REQUESTED** [review]
In the beginning of the ipynb file, please provide the links of all references, such as openai whispter, Google Recognition, and Facebook's Wav2Vec Model. The github pages or main websites should be fine!

Moreover, it would be better to compare three models at the end of the file, such as accuracy and speed from the example video.

**Comment by roh-it** [comment]
@ChiragBellara can we add parameter specifications for the methods written? Something like what should be the input parameters for a method(int/string/object )

**Review by silbunsa — APPROVED** [review]
Looks Good!

**Review by SaiSurajMatta — APPROVED** [review]
No Changes from my side.

**Review by roh-it — CHANGES_REQUESTED** [review]
Can we have parameter definitions, like which input should we pass to methods?

**Comment by ChiragBellara** [comment]
> In the beginning of the ipynb file, please provide the links of all references, such as openai whispter, Google Recognition, and Facebook's Wav2Vec Model. The github pages or main websites should be fine!
> 
> Moreover, it would be better to compare three models at the end of the file, such as accuracy and speed from the example video.

I have added the references to the Models used at the start of the file.
As for the comparison metrics, I have added a table at the end of the file to compare the Times of Execution for each model. Since there was no transcription available for the test video, I will change the test video to one that has a transcription and add a separate code for text comparison to get the total accuracy. As that might take a day or two, I would close this pull request and work on that separately.

**Comment by ChiragBellara** [comment]
> Can we have parameter definitions, like which input should we pass to methods?

I have added the parameter definitions to the relevant functions. However, since this is not the end-to-end implementation, there is no starting function or end function. Each of them has to be executed individually. I'll try to write an end-to-end implementation for the same as a separate code. So if we can close this pull request then I can work on that separately and include that in the next pull request.

**Comment by zeshengchen** [comment]
> > In the beginning of the ipynb file, please provide the links of all references, such as openai whispter, Google Recognition, and Facebook's Wav2Vec Model. The github pages or main websites should be fine!
> > Moreover, it would be better to compare three models at the end of the file, such as accuracy and speed from the example video.
> 
> I have added the references to the Models used at the start of the file. As for the comparison metrics, I have added a table at the end of the file to compare the Times of Execution for each model. Since there was no transcription available for the test video, I will change the test video to one that has a transcription and add a separate code for text comparison to get the total accuracy. As that might take a day or two, I would close this pull request and work on that separately.

Thanks for the update!

**Review by zeshengchen — APPROVED** [review]

**Review by roh-it — APPROVED** [review]

**Pull request merged**
