### PR TITLE
Created new folder for Requirements and added the Requirements file to it.

### PR DESCRIPTION
**Pull request by ChiragBellara**

### CODE REVIEW

**Review by SaiSurajMatta — APPROVED** [review]
Looks good.

**Review by zeshengchen — APPROVED** [review]

**Review by roh-it — APPROVED** [review]

**Comment by silbunsa** [comment]
Good to go 🤌

**Comment by zeshengchen** [comment]
@ChiragBellara Please note that @silbunsa has not approved this pull request, but you have completed the pull request. 

For future pull requests, please wait until all other group members approve the pull request before you completing it.

**Comment by zeshengchen** [comment]
> Good to go 🤌

Please peer review it early and then approve it!

**Pull request merged**
